all: undirectedGraphdriver

undirectedGraphdriver: undirectedGraphtest.cpp Graph.h Graph.cpp
	g++ -std=c++11 -o undirectedGraphdriver undirectedGraphtest.cpp Graph.cpp

clean:
	rm undirectedGraphdriver